project:
  type: book
  render:  # only render index.qmd and .qmd files in chapters/
    - "index.qmd"
    - "chapters/*.qmd"
  execute-dir: project  # working directory is always root of project
  output-dir: "docs/"

book:
  # Metadata (fill this in):
  repo-url: "https://github.com/ucdavisdatalab/workshop_quarto_accessibility"
  title: "How to Improve Accessibility of Datalab Workshops"
  author:
    - "Wesley Brooks"
  chapters:
    - "index.qmd"
    # List your chapters in order here.
    - "chapters/01_principles.qmd"
    - "chapters/02_technologies.qmd"
    - "chapters/03_design_considerations.qmd"
    - "chapters/04_audit_of_r_basics.qmd"
    - "chapters/05_solutions.qmd"
    - "chapters/references.qmd"
    - "chapters/assessment.qmd"

  # Formatting (be careful about changing these):
  date: now
  repo-actions: [issue, source]
  sidebar:
    logo: "images/datalab-logo-full-color-rgb-1.png"
    logo-alt: "The logo of the UC Davis DataLab."
    logo-href: "https://datalab.ucdavis.edu/"

format:
  html:
    theme: cosmo
    toc: true
    sploot: splat
    template-partials: 
      - "templates/toc.html"
  # Uncomment to also generate a PDF:
  # pdf: default

# Uncommentt if you want to use BibTex or BibLaTeX references.
# bibliography: references.bib

# Cache computations from each chapter:
execute:
  freeze: auto
